// Cyberdeck Enclosure v2 — generated by cyberdeck_core (Rust)
// Style: industrial, Colors: ["black", "yellow", "silver", "red"]

$fn = 32;

w = 120.00;
h = 40.00;
d = 90.00;

module enclosure_body() { color("#1A1A1A") {
                minkowski() {
        cube([112.00, 16.00, 82.00], center=true);
        sphere(r=4.00, $fn=24);
    }
}

        } }

module enclosure_lid() { color("#1A1A1A") {
                minkowski() {
        cube([114.00, 0.10, 84.00], center=true);
        sphere(r=3.00, $fn=24);
    }
}

        } }

module vent_slots() {
    translate([-46.67, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([-33.33, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([-20.00, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([-6.67, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([6.67, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([20.00, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([33.33, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
    translate([46.67, 0, d/2 - 3])
        cube([1.5, 25, 1], center=true);
}

module cable_channel() {
    color("#505050") {
        difference() {
            translate([-120.00/2 + 3, 0, -h/2 + 2])
                cube([4, 90.00 - 10, 4], center=true);
            translate([-120.00/2 + 3, 0, -h/2 + 2])
                cube([2.4, 90.00 - 8, 5], center=true);
        }
    }
}

module hinge() {
    color("#808080") {
        translate([0, 0, -h/2]) {
            cube([w - 20, 3, 0.8], center=true);
        }
    }
}

module standoffs() {
    color("#C0C0C0") {
        for (pos = [[-30, -25], [30, -25], [-30, 25], [30, 25], [-15, 35], [15, 35]]) {
            translate([pos[0], pos[1], -h/2 + 1])
                difference() {
                    cylinder(r=3.2, h=6, center=true, $fn=20);
                    translate([0, 0, -1])
                        cylinder(r=1.3, h=8, center=true, $fn=12);
                }
        }
    }
}

module io_cutouts() {
    // HDMI
    translate([w/2 - 2, -8, 2])
        cube([5, 14, 7], center=true);
    // USB ports × 2
    translate([w/2 - 2, 7, 2])
        cube([5, 13, 6], center=true);
    translate([w/2 - 2, 22, 2])
        cube([5, 13, 6], center=true);
    // Power barrel / USB-C
    translate([w/2 - 2, -22, 2])
        cube([6, 10, 8], center=true);
    // 3.5mm audio
    translate([w/2 - 2, -35, 2])
        cube([5, 8, 6], center=true);
    // GPIO access
    translate([-w/2 + 2, 0, 2])
        cube([8, 40, 4], center=true);
}

module display_bezel() {
    difference() {
        translate([0, 0, h/2])
            cube([90.00, 58.50, 2], center=true);
        translate([0, 0, h/2 + 1])
            cube([90.00 - 8, 58.50 - 8, 4], center=true);
    }
}

module lid_latch() {
    translate([0, d/2 - 5, 0])
        cube([12, 3, 3], center=true);
}

module accent_lines() {
    color("#FFD700") {
        translate([0, -33.00, h/2 + 2])
            cube([w - 24, 1.2, 0.5], center=true);
        translate([0, -11.00, h/2 + 2])
            cube([w - 24, 1.2, 0.5], center=true);
        translate([0, 11.00, h/2 + 2])
            cube([w - 24, 1.2, 0.5], center=true);
        translate([0, 33.00, h/2 + 2])
            cube([w - 24, 1.2, 0.5], center=true);
    }
}

// ===== ASSEMBLY =====
difference() {
    enclosure_body();

    // Cut out SBC area
    translate([0, 0, -h/4])
        cube([65, 56, h/2], center=true);

    // Cut out display area
    translate([0, 0, h/4])
        cube([w * 0.7, d * 0.6, h/2], center=true);

    // Ventilation
    translate([0, 0, h/4]) vent_slots();

    // I/O cutouts
    io_cutouts();

    // Cable channel slot
    translate([0, 0, -h/4])
        cable_channel();

    // Screw holes
    for (corner = [[-w/2 + 6, -d/2 + 6], [w/2 - 6, -d/2 + 6],
                   [-w/2 + 6, d/2 - 6], [w/2 - 6, d/2 - 6]]) {
        translate([corner[0], corner[1], 0])
            cylinder(r=1.6, h=h+1, center=true, $fn=16);
    }
}

// Standoffs
standoffs();

// Lid
translate([0, 0, h/2 + 1.5]) {
    enclosure_lid();
    display_bezel();
    lid_latch();
}

// Hinge
hinge();

// Accent lines
translate([0, 0, h/2 + 2])
    accent_lines();
